/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSalesRouteImport } from './routes/_app.sales'
import { Route as AppProductionsRouteImport } from './routes/_app.productions'
import { Route as AppMortalitiesRouteImport } from './routes/_app.mortalities'
import { Route as AppHppRouteImport } from './routes/_app.hpp'
import { Route as AppFlocksRouteImport } from './routes/_app.flocks'
import { Route as AppExpensesRouteImport } from './routes/_app.expenses'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAssetsRouteImport } from './routes/_app.assets'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppProductionsRoute = AppProductionsRouteImport.update({
  id: '/productions',
  path: '/productions',
  getParentRoute: () => AppRoute,
} as any)
const AppMortalitiesRoute = AppMortalitiesRouteImport.update({
  id: '/mortalities',
  path: '/mortalities',
  getParentRoute: () => AppRoute,
} as any)
const AppHppRoute = AppHppRouteImport.update({
  id: '/hpp',
  path: '/hpp',
  getParentRoute: () => AppRoute,
} as any)
const AppFlocksRoute = AppFlocksRouteImport.update({
  id: '/flocks',
  path: '/flocks',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/assets': typeof AppAssetsRoute
  '/dashboard': typeof AppDashboardRoute
  '/expenses': typeof AppExpensesRoute
  '/flocks': typeof AppFlocksRoute
  '/hpp': typeof AppHppRoute
  '/mortalities': typeof AppMortalitiesRoute
  '/productions': typeof AppProductionsRoute
  '/sales': typeof AppSalesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/assets': typeof AppAssetsRoute
  '/dashboard': typeof AppDashboardRoute
  '/expenses': typeof AppExpensesRoute
  '/flocks': typeof AppFlocksRoute
  '/hpp': typeof AppHppRoute
  '/mortalities': typeof AppMortalitiesRoute
  '/productions': typeof AppProductionsRoute
  '/sales': typeof AppSalesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/assets': typeof AppAssetsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/flocks': typeof AppFlocksRoute
  '/_app/hpp': typeof AppHppRoute
  '/_app/mortalities': typeof AppMortalitiesRoute
  '/_app/productions': typeof AppProductionsRoute
  '/_app/sales': typeof AppSalesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/assets'
    | '/dashboard'
    | '/expenses'
    | '/flocks'
    | '/hpp'
    | '/mortalities'
    | '/productions'
    | '/sales'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/assets'
    | '/dashboard'
    | '/expenses'
    | '/flocks'
    | '/hpp'
    | '/mortalities'
    | '/productions'
    | '/sales'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/assets'
    | '/_app/dashboard'
    | '/_app/expenses'
    | '/_app/flocks'
    | '/_app/hpp'
    | '/_app/mortalities'
    | '/_app/productions'
    | '/_app/sales'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/productions': {
      id: '/_app/productions'
      path: '/productions'
      fullPath: '/productions'
      preLoaderRoute: typeof AppProductionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mortalities': {
      id: '/_app/mortalities'
      path: '/mortalities'
      fullPath: '/mortalities'
      preLoaderRoute: typeof AppMortalitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hpp': {
      id: '/_app/hpp'
      path: '/hpp'
      fullPath: '/hpp'
      preLoaderRoute: typeof AppHppRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flocks': {
      id: '/_app/flocks'
      path: '/flocks'
      fullPath: '/flocks'
      preLoaderRoute: typeof AppFlocksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets': {
      id: '/_app/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAssetsRoute: typeof AppAssetsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppFlocksRoute: typeof AppFlocksRoute
  AppHppRoute: typeof AppHppRoute
  AppMortalitiesRoute: typeof AppMortalitiesRoute
  AppProductionsRoute: typeof AppProductionsRoute
  AppSalesRoute: typeof AppSalesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssetsRoute: AppAssetsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppFlocksRoute: AppFlocksRoute,
  AppHppRoute: AppHppRoute,
  AppMortalitiesRoute: AppMortalitiesRoute,
  AppProductionsRoute: AppProductionsRoute,
  AppSalesRoute: AppSalesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
